### ISSUE TITLE
[Feature] Configure API user for PowerBI dashboard

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#156]
**Is your feature request related to a problem? Please describe.**
We want to avoid any infiltration and leak of the personal data when linking EspoCRM to the dashboard. That's why we have to secure the API. 

**User Story**
As 510
I want to secure the API connection between EspoCRM and PowerBI
So that I ensure the personal data are safeguarded.

**Describe the solution you'd like**
Configure a unique API token for the PowerBI dashboard. It needs to not give any access to personal identifiable information (PII) but will use only the relevant data for the dashboard.

**Comment by leoniecazemier** [comment]
Additional information/tips from Chris Coutinho (ORTEC):
The primary security concern is the integrity of the data. The database should not permit unrestricted access, and ideally only be accessible from the PHP application itself to reduce the theoretical attack surface. Since you're planning on using the REST API via PowerBI, I would reiterate the need for your team to generate a unique API token for the PowerBI dashboard(s), which has read-only access to the tables required by the analysts. EspoCRM provides functionality via the Admin portal to organize user/role access, which I believe your team is already utilizing and should allow you to secure the data ([link](https://docs.espocrm.com/administration/roles-management/))
