### ISSUE TITLE
[Feature] role-based landing page

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#52]
**Is your feature request related to a problem? Please describe.**
not a problem but data-responsible way of showing data.

**User Story**
As a HQ HRC worker
I want to be the only one to view the dashboard of the complete operation
So that I can effectively report on it. 

**Describe the solution you'd like**
Only HQ HRC users (and team leads) should be able to see the dashboard.

**Comment by LauraMedendorp** [comment]
I made a rol: HQ HRC worker.
I will ask Fernando how to handle this item

**Comment by LauraMedendorp** [comment]
I made a role and a team: _HQ HRC worker_.
When a new user is added, he/she does not see the dashboard, but if the user is added to the team and role _HQ HRC Worker_ and the dashboard is again deployed to the team _HQ HRC Workers_, the user is able to see the dashboard. However, when the user gets access ones, it is hard to not show the dashboard anymore. When the role and teams are removed from the user, the user can still see the dashboard (even when the dashboard is again deployed to the team where the user is no longer part of).

**Comment by corina444** [comment]
During the sprint review of 2022.05.18, the HRC team indicated that it happens that people leave HQ and go back to the field. In these cases, they should not be able to see the dashboard. The HRC team exclusively asked us to look into this on how to solve it. We have to see if there is a workaround @LauraMedendorp, anything you can think of? The only other option I can think of is to uncouple the dashboard from the CRM system completely. This is an easy workaround, but I don't know where the dashboard would be hosted and how access can be regulated. @tijsziere , could you give us your insights?

**Comment by LauraMedendorp** [comment]
I can think of 2 solutions:
1. As you already said, deploy the dashboard outside of the tool. I can imagne that the HQ workers should also not see a lot within the tool due to privacy reasons? Because in that case I think it is just as usefull to deploy this dashboard somewhere else, because they would otherwise also only see the home page? 
2. Deploy the dashboard again every X weeks or when the HQ team changes. By making a new dashboard template and making sure the Team is up-to-date and deploy is to them only, only the people that still work at HQ could see the dashboard. This isn't a lot of work and is an relatively easy task. In this way, it can no longer happen that someone sees the dashboard when they have another job.

**Comment by corina444** [comment]
To answer to your solutions:
1. You are right in saying that data protection is a big argument in deploying the dashboard somewhere other than the CRM system itself, as HQ workers have nothing to do with the medical information of individuals. I think it's something we should discuss with the HRC team, but my preference goes to having the dashboard seperate from the CRM system. I will put this as an item in the agenda for our upcoming meeting. 
2. If the HRC team decides to keep the dashboard in the CRM system, then this sounds like a good solution. Thanks for the suggestion! We will see what they decide and according to that, open a new issue in which we set up a slide deck to explain to them how to do what you suggest.
